version: '3.7'

services:
  backend:
    image: ioannisnoukakis9390/ragnachatserver:latest
    environment:
      CORS_ALLOWED_HOSTS.1: ${CORS_ALLOWED_HOST}
      APP_VERSION: ${APP_VERSION}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      JWT_SECRET: ${JWT_SECRET}
      MONGODB_URL: ${MONGODB_URL}
    ports:
    - 9000:9000

networks:
  mongo-dev-net:
